# Global config
global:
  scrape_interval: 15s
  evaluation_interval: 30s

# Alertmanager config
#alerting:
#  alertmanagers:
#    - static_configs:
#      - targets:
#        - alertmanager: 9093

# Scrape config
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "tns_app"
    static_configs:
      - targets: ["app:80"]
    # Override global settings
    scrape_interval: 5s

  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "mysqld-exporter"
    static_configs:
      - targets: ["mysqld-exporter:9104"]
